# Site settings
author: Georgette Class-Peters
title: 
header-img: img/home-bg.png
email: georgycp@udel.edu
copyright_name: Georgette Class-Peters
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Efuathesingingdeveloper

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
